
#Client Regeneration Settings
[client]

	#Skin Settings
	[client.skin]
		#Toggle whether the mod downloads it's own pack of Doctor who Skins
		downloadInternalSkins = true
		#Disabling this will disable skin changing for you and you will retain your Mojang one
		changeMySkin = true
		#Toggle whether a bunch of trending skins are downloaded from NameMC
		downloadTrendingSkins = false
		#Changes the players perspective on regeneration
		changePerspective = false
		#Toggle whether your hand has the chance of inverting after a regen
		changeHand = true
		#This is where the regeneration skin folder will be generated, the default is './', the path MUST NOT end in /
		skinDir = "."
		#Toggle whether the mod downloads your past skins from NameMC
		downloadPastSkins = false

		#Misc Settings
		[client.skin.misc]
			#Toggle whether Timelords second head layers render, as some look good without and some look good with, I just leave this decision up to you
			timelordRenderSecondLayers = true

