
["Tardis Configurations"]
	#List of dimensions Tardis cannot travel to, everything else is allowed
	#Seperate every entry except the last one with commas
	blacklistedDims = []

["Entities to Kill when changing TARDIS interior"]
	things_to_kill = [""]

["Vortex Manipulator (VM) Configurations"]
	#List of dimensions the VM cannot travel to, everything else is allowed
	#Seperate every entry except the last one with commas
	blacklistedVMDims = ["tardis"]
	#List of dimensions the VM can travel to, anything else is not allowed
	#Seperate every entry except the last one with commas
	whitelistedVMDims = ["minecraft:overworld", "minecraft:nether", "minecraft:the_end"]
	#Toggle whether to use the Whitelist. By default, uses the Blacklist
	toggleVMWhitelistDims = false

["Sonic Screwdriver"]

	["Sonic Screwdriver".Laser]
		#Toggle where the Laser setting burns things
		laser_fire = true

	["Sonic Screwdriver"."Block Interactions"]
		#Toggle whether sonics can open Trap doors
		open_trapdoors = true
		#Toggle whether sonics can detonate TNT
		detonate_tnt = true
		#Toggle whether sonics can toggle Lamps
		redstone_lamps = true
		#Toggle whether sonics can open doors
		open_doors = true
		#Toggle whether enable/disable redstone
		redstone = true

	["Sonic Screwdriver".Tardis]
		#Toggle whether sonics can tell the Tardis where to land
		coordinate_tardis = true

	["Sonic Screwdriver"."Entity Interactions"]
		#Toggle whether sonics can detonate Creepers
		detonate_creeper = true
		#Toggle whether sonics can Shear Sheep
		shear_sheep = true
		#Toggle whether sonics can dismantle Skeleton like entities
		dismantle_skeletons = true
		#Toggle whether sonics can ink Squids
		ink_squid = true

